name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Ali Container
        run: |
          docker login --username=${{ secrets.ALI_CONTAINER_USER }} --password="${{ secrets.ALI_CONTAINER_PWD }}" registry.cn-hongkong.aliyuncs.com

      - name: Build Docker image
        run: |
          docker build -t registry.cn-hongkong.aliyuncs.com/runnable-run/pdf2html-web:latest .

      - name: Push Docker image to Ali Container
        run: |
          docker push registry.cn-hongkong.aliyuncs.com/runnable-run/pdf2html-web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Set up KUBE_CONFIG
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > K3S_KUBE_CONFIG.yaml
          chmod 600 K3S_KUBE_CONFIG.yaml

      - name: Deploy to K3s
        run: |
          kubectl --kubeconfig=K3S_KUBE_CONFIG.yaml apply -f k8s-deployment.yaml
          kubectl --kubeconfig=K3S_KUBE_CONFIG.yaml rollout restart deployment pdf2html-web -n gongjudev